"""Shared test fixtures."""

import pytest


@pytest.fixture
def sample_features_json():
    """A realistic features_json dict matching the current ExtractedSpeciesFeatures schema."""
    return {
        "scientific_name": "Amanita muscaria",
        "species_epithet": "muscaria",
        "common_names": ["Fly agaric"],
        "synonyms": [],
        "kingdom": "Fungi",
        "phylum": "Basidiomycota",
        "order": "Agaricales",
        "family": "Amanitaceae",
        "genus": "Amanita",
        "cap": {
            "shape": "convex",
            "colors": ["scarlet red", "orange-red", "yellow-orange"],
            "color_faded": None,
            "color_pattern": "uniform",
            "surface_texture": "smooth",
            "surface_moisture": "dry",
            "bruising_color": None,
            "scales_or_warts": "warts",
            "margin_type": "striate",
            "margin_lined_at_maturity": True,
            "central_depression": False,
            "diameter_min_cm": 8.0,
            "diameter_max_cm": 20.0,
        },
        "hymenium": {
            "type": "gills",
        },
        "gills": {
            "attachment": "free",
            "spacing": "crowded",
            "color": "white",
            "color_with_age": "white, not changing",
            "thickness": "thin",
            "texture": "normal",
        },
        "pores": {
            "color": None,
            "color_with_age": None,
            "bruising_color": None,
            "density_per_mm": None,
        },
        "tubes": {
            "depth_mm": None,
        },
        "stem": {
            "color": "white",
            "color_with_age": "yellowish with age",
            "surface_texture": "fibrillose",
            "reticulation": "none",
            "shape": "bulbous",
            "attachment_position": "central",
            "consistency": "firm",
            "hollow_or_solid": "stuffed",
            "base_color": "white",
            "bruising_color": None,
            "basal_mycelium_color": "white",
            "finger_stain_color": None,
            "height_min_cm": 8.0,
            "height_max_cm": 20.0,
            "diameter_min_cm": 1.0,
            "diameter_max_cm": 3.0,
        },
        "veil": {
            "present": True,
            "type": "partial",
            "cortina_present": False,
            "shape": "pendant",
            "color": "white",
            "ring_position": "apical",
            "ring_persistence": "persistent",
            "ring_mobility": "fixed",
        },
        "volva": {
            "present": True,
            "type": "friable",
            "color": "white",
            "shape": "sack-like",
        },
        "flesh": {
            "color": "white",
            "bruising_color": None,
            "odor": "none",
            "taste": "mild",
            "texture": "firm",
            "quantity": "moderate",
            "hyphal_structure": "homoiomerous",
            "cap_stem_consistency": "homogeneous",
            "latex_presence": False,
            "latex_color": None,
        },
        "spore_print_color": "white",
        "spore": {
            "shape": "broadly_ellipsoid",
            "length_min_um": 9.0,
            "length_max_um": 13.0,
            "width_min_um": 6.5,
            "width_max_um": 9.0,
            "ornamentation": "smooth",
            "spine_length_um": None,
            "spine_base_width_um": None,
            "amyloidity": "inamyloid",
            "color_in_KOH": "hyaline",
        },
        "microscopic": {
            "basidia_spore_count": "4-spored",
            "cheilocystidia_shape": None,
            "cheilocystidia_dims_um": None,
            "pleurocystidia_shape": None,
            "pleurocystidia_dims_um": None,
            "cystidia_color_in_KOH": None,
            "pileipellis_type": "ixocutis",
            "pileipellis_element_width_um": None,
            "pileipellis_terminal_cell_shape": None,
        },
        "chemical": {
            "KOH_cap": "negative",
            "KOH_flesh": None,
            "NH4OH_cap": None,
            "NH4OH_flesh": None,
            "FeSO4_cap": None,
            "FeSO4_flesh": None,
        },
        "overall_size_class": "large",
        "overall_body_form": "agaricoid",
        "growth_habit": "solitary",
        "ecology": {
            "trophic_mode": "mycorrhizal",
            "substrate": "soil",
            "associated_trees": ["birch", "pine", "spruce"],
            "fruiting_months": ["July", "August", "September", "October", "November"],
            "geographic_regions": ["Europe", "North America", "Asia"],
            "altitude_notes": "montane",
            "growth_position": "terrestrial",
        },
        "edibility_status": "toxic",
        "known_toxins": ["ibotenic acid", "muscimol"],
        "known_lookalikes": ["Amanita caesarea"],
        "extraction_notes": None,
    }
