"""Shared test fixtures."""

import pytest


@pytest.fixture
def sample_features_json():
    """A realistic features_json dict matching the current ExtractedSpeciesFeatures schema."""
    return {
        "scientific_name": "Amanita muscaria",
        "species_epithet": "muscaria",
        "common_names": ["Fly agaric"],
        "synonyms": [],
        "kingdom": "Fungi",
        "phylum": "Basidiomycota",
        "order": "Agaricales",
        "family": "Amanitaceae",
        "genus": "Amanita",
        "cap": {
            "shape": "convex to broadly convex, then flat",
            "colors": ["scarlet red", "orange-red", "yellow-orange"],
            "color_faded": None,
            "hygrophanous": False,
            "color_pattern": "uniform, paler toward margin",
            "surface_texture": "smooth, viscid when moist",
            "scales_or_warts": "white universal veil remnants as patches",
            "margin_type": "striate at maturity",
            "margin_lined_at_maturity": True,
            "central_depression": False,
            "diameter_min_cm": 8.0,
            "diameter_max_cm": 20.0,
        },
        "hymenium": {
            "type": "gills",
        },
        "gills": {
            "attachment": "free",
            "spacing": "crowded",
            "color": "white",
            "color_with_age": "white, not changing",
            "thickness": "thin",
            "texture": "normal",
        },
        "pores": {
            "color": None,
            "color_with_age": None,
            "bruising_color": None,
            "density_per_mm": None,
        },
        "tubes": {
            "depth_mm": None,
        },
        "stem": {
            "color": "white",
            "color_with_age": None,
            "surface_texture": "smooth to slightly fibrous, with shaggy base",
            "reticulation": "none",
            "shape": "equal, with bulbous base",
            "consistency": "firm",
            "hollow_or_solid": "stuffed becoming hollow",
            "base_color": "white",
            "basal_mycelium_color": "white",
            "finger_stain_color": None,
            "height_min_cm": 8.0,
            "height_max_cm": 20.0,
            "diameter_min_cm": 1.0,
            "diameter_max_cm": 3.0,
        },
        "veil": {
            "present": True,
            "type": "partial",
            "cortina_present": False,
            "shape": "pendant, skirt-like",
            "color": "white",
        },
        "volva": {
            "present": True,
            "type": "friable remnants",
            "shape": "rings of scales around bulbous base",
            "color": "white",
        },
        "flesh": {
            "color": "white",
            "bruising_color": None,
            "odor": "not distinctive",
            "taste": "not distinctive",
            "texture": "firm",
            "quantity": "moderate",
        },
        "spore_print_color": "white",
        "spore": {
            "shape": "globose to broadly ellipsoid",
            "length_min_um": 9.0,
            "length_max_um": 13.0,
            "width_min_um": 6.5,
            "width_max_um": 9.0,
            "ornamentation": "smooth",
            "spine_length_um": None,
            "spine_base_width_um": None,
            "amyloidity": "inamyloid",
            "color_in_KOH": "hyaline",
        },
        "microscopic": {
            "basidia_spore_count": "4-spored",
            "cheilocystidia_shape": None,
            "cheilocystidia_dims_um": None,
            "pleurocystidia_shape": None,
            "pleurocystidia_dims_um": None,
            "cystidia_color_in_KOH": None,
            "pileipellis_type": "ixocutis",
            "pileipellis_element_width_um": None,
            "pileipellis_terminal_cell_shape": None,
        },
        "chemical": {
            "KOH_cap": None,
            "KOH_flesh": None,
            "NH4OH_cap": None,
            "NH4OH_flesh": None,
            "FeSO4_cap": None,
            "FeSO4_flesh": None,
        },
        "overall_size_class": "large",
        "ecology": {
            "trophic_mode": "mycorrhizal",
            "habitat_types": ["deciduous forest", "coniferous forest", "mixed woodland"],
            "substrate": "soil",
            "associated_trees": ["birch", "pine", "spruce"],
            "fruiting_seasons": ["late summer", "autumn"],
            "fruiting_months": "July–November",
            "geographic_regions": ["Europe", "North America", "Asia"],
            "altitude_notes": "sea level to montane",
            "growth_pattern": "solitary or scattered",
            "growth_position": "terrestrial",
            "microhabitat_notes": None,
        },
        "edibility_status": "toxic",
        "known_toxins": ["ibotenic acid", "muscimol"],
        "known_lookalikes": ["Amanita caesarea"],
        "extraction_notes": None,
    }
